--- 
- hosts: localhost 
  connection: ssh
  gather_facts: no
  become: true 
  user: ansible
  tasks:
    - name: Record the Date_Time when the playbook executes
      raw: /usr/bin/date > /home/ansible/DevOps_Training/playbooks/playbook_start.log
    - name: Install the apache
      yum: name=httpd state=latest
    - name: start the httpd service
      service: name=httpd state=restarted
    - name: verify the service running
      command: systemctl status httpd
      register: result
    - debug: var=result
    - name: log the packages
      raw: yum list installed > /home/ansible/DevOps_Training/playbooks/installed.log
    - name: Record the Date_time whent he playbook ends
      raw: /usr/bin/date > /home/ansible/DevOps_Training/playbooks/playbook_end.log

